# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DirMonitoring.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DirMonitoring(object):
    def setupUi(self, DirMonitoring):
        DirMonitoring.setObjectName("DirMonitoring")
        DirMonitoring.resize(539, 561)
        self.centralwidget = QtWidgets.QWidget(DirMonitoring)
        self.centralwidget.setObjectName("centralwidget")
        self.StopMonitor = QtWidgets.QPushButton(self.centralwidget)
        self.StopMonitor.setGeometry(QtCore.QRect(180, 510, 181, 41))
        self.StopMonitor.setObjectName("StopMonitor")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.DirPath = QtWidgets.QLabel(self.centralwidget)
        self.DirPath.setGeometry(QtCore.QRect(40, 40, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DirPath.setFont(font)
        self.DirPath.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DirPath.setObjectName("DirPath")
        self.DirPath.setAlignment(QtCore.Qt.AlignCenter)
        #self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 521, 391))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        DirMonitoring.setCentralWidget(self.centralwidget)

        self.retranslateUi(DirMonitoring)
        QtCore.QMetaObject.connectSlotsByName(DirMonitoring)

    def retranslateUi(self, DirMonitoring):
        _translate = QtCore.QCoreApplication.translate
        DirMonitoring.setWindowTitle(_translate("DirMonitoring", "Antivirus"))
        self.StopMonitor.setText(_translate("DirMonitoring", "Прервать мониторинг"))
        self.label.setText(_translate("DirMonitoring", "Мониторинг директории"))
        self.DirPath.setText(_translate("DirMonitoring", "Путь к директории"))
        self.label_2.setText(_translate("DirMonitoring", "История изменений"))
