# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'antivirus.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 273)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ScanButton = QtWidgets.QPushButton(self.centralwidget)
        self.ScanButton.setGeometry(QtCore.QRect(140, 140, 261, 51))
        self.ScanButton.setObjectName("ScanButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(500, 70, 27, 22))
        self.toolButton.setObjectName("toolButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 70, 261, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.MonitorButton = QtWidgets.QPushButton(self.centralwidget)
        self.MonitorButton.setGeometry(QtCore.QRect(10, 210, 241, 51))
        self.MonitorButton.setObjectName("MonitorButton")
        self.SchedButton = QtWidgets.QPushButton(self.centralwidget)
        self.SchedButton.setGeometry(QtCore.QRect(290, 210, 241, 51))
        self.SchedButton.setObjectName("SchedButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ServiceStatus = QtWidgets.QLabel(self.centralwidget)
        self.ServiceStatus.setGeometry(QtCore.QRect(230, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.ServiceStatus.setFont(font)
        self.ServiceStatus.setObjectName("ServiceStatus")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Antivirus"))
        self.ScanButton.setText(_translate("MainWindow", "Отсканировать файлы"))
        self.label.setText(_translate("MainWindow", "Выберите директорию"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.MonitorButton.setText(_translate("MainWindow", "Мониторинг директории"))
        self.SchedButton.setText(_translate("MainWindow", "Сканирование по расписанию"))
        self.label_2.setText(_translate("MainWindow", "Статус сервиса антивируса:"))
        self.ServiceStatus.setText(_translate("MainWindow", "не запущен"))
